version: '3'

services:
  rtmp-rtsp-converter:
    build: .
    container_name: rtmp-rtsp-converter
    ports:
      - '${API_PORT}:${API_PORT}'
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - PORT=${API_PORT}
      - RTMP_PORT=${RTMP_PORT}
      - RTMP_CHUNK_SIZE=60000
      - RTSP_PORT=${RTSP_PORT}
      - HTTP_PORT=${HLS_PORT}
      - LOG_LEVEL=info
      - LOG_DIR=./logs
      - DOCKER_ENV=true
    depends_on:
      - mediamtx
    networks:
      - stream-network

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - '${RTMP_PORT}:${RTMP_PORT}'
      - '${RTSP_PORT}:${RTSP_PORT}'
      - '${HLS_PORT}:${HLS_PORT}'
      - '${WEBRTC_PORT}:${WEBRTC_PORT}'
      - '${MEDIAMTX_API_PORT}:${MEDIAMTX_API_PORT}'
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
    networks:
      - stream-network

networks:
  stream-network:
    driver: bridge
